#!/usr/bin/env python3
"""Export real clients and their bookings out of Bloowatch, to fill the app up.

    python3 export_clients.py --out ../app/clients.json --count 100

This reads the orders list rather than the customers list, because an order
carries the customer *and* what they bought -- the products, the dates, the
board that actually went out and what was paid. A customer on their own is a
name with nothing behind it, and the point of this file is to have something
to click on.

THIS FILE HOLDS REAL PEOPLE'S NAMES, PHONE NUMBERS AND EMAIL ADDRESSES. It is
in .gitignore and must stay there, and the page built with it should not be
put on a public URL. Everything else the app needs (catalog.json) is free of
personal data on purpose; this one cannot be.
"""
import argparse
import datetime as dt
import json
import sys

from daily_report import BloowatchError, login
from export_dataset import _get, _rows, school_id

PAGE = 100
MAX_PAGES = 40


def num(v):
    try:
        return round(float(str(v).replace("(", "-").replace(")", "")), 2)
    except (TypeError, ValueError):
        return None


def when(v):
    """'Sat, 29 Aug 2026 09:31:25 -0500' -> ('2026-08-29', '09:31')."""
    if not v:
        return None, None
    try:
        d = dt.datetime.strptime(str(v)[:25].strip(), "%a, %d %b %Y %H:%M:%S")
    except ValueError:
        return None, None
    return d.date().isoformat(), d.strftime("%H:%M")


def person(c):
    return " ".join(x for x in ((c.get("first_name") or "").strip(),
                                (c.get("last_name") or "").strip()) if x).strip()


def build(count):
    s, base = login()
    sid = school_id(s, base)

    clients, by_id, bookings = [], {}, []
    pages = 0
    while len(clients) < count and pages < MAX_PAGES:
        rows = _rows(_get(s, base, f"/schools/{sid}/orders/",
                          offset=pages * PAGE, limit=PAGE))
        pages += 1
        if not rows:
            break
        for o in rows:
            c = o.get("customer") or {}
            cid = c.get("id")
            name = person(c)
            if not cid or not name:
                continue
            if cid not in by_id:
                if len(clients) >= count:
                    continue
                # their guest addresses are generated, not given: an address
                # like guest_josh_shokogi.kteyk@bloowatch.com is not a way to
                # reach anyone, so it is left out rather than carried across
                email = (c.get("email") or "").strip()
                if c.get("email_autogenerated") or "@bloowatch.com" in email:
                    email = ""
                rec = {
                    "srcId": cid,
                    "name": name,
                    "email": email,
                    "phone": (c.get("phone") or "").strip(),
                    "country": (c.get("country") or c.get("phone_country") or "").upper(),
                    "language": c.get("language") or "",
                    "city": c.get("city") or "",
                    "notes": (c.get("note") or "").strip(),
                }
                # The customer inside an order is a light copy: its totals and
                # creation time come back empty. They are not written down as
                # zeroes -- the app adds up what the person actually bought
                # from the bookings below, which is the same number arrived at
                # honestly.
                by_id[cid] = rec
                clients.append(rec)

            date, _ = when(o.get("date_placed"))
            lines = []
            for l in (o.get("lines") or []):
                p = l.get("product") or {}
                sd, st = when(l.get("starting_date"))
                ed, _et = when(l.get("ending_date"))
                hours = None
                if sd and ed and sd == ed and st:
                    _s, e2 = when(l.get("ending_date"))
                    try:
                        h = (int(e2[:2]) * 60 + int(e2[3:])) - \
                            (int(st[:2]) * 60 + int(st[3:]))
                        hours = round(max(0, h) / 60.0, 2) or None
                    except (TypeError, ValueError):
                        hours = None
                rents = [r.get("unit_name") for r in (l.get("rents") or [])
                         if r.get("unit_name")]
                # Who is on the water for this line, and it is per line rather
                # than per order: oria group's four people are on the course,
                # a fifth is on a single lesson and a sixth on the photo shoot.
                # "P1 oria group" is Bloowatch's own placeholder for a seat
                # nobody named, so it is kept as the name it is.
                people = []
                for c in (l.get("customers") or []):
                    cc = c.get("customer") or {}
                    nm = " ".join(x for x in ((cc.get("first_name") or "").strip(),
                                              (cc.get("last_name") or "").strip())
                                  if x).strip()
                    if nm:
                        people.append(nm)
                lines.append({
                    "product": p.get("name") or p.get("title") or "",
                    "qty": l.get("quantity") or 1,
                    "pax": l.get("num_items") or 1,
                    "price": num(l.get("unit_price_incl_tax")),
                    "total": num(l.get("line_price_incl_tax")),
                    "discount": num(l.get("discount_incl_tax")) or 0,
                    "date": sd, "time": st, "until": ed,
                    "hours": hours,
                    "units": rents,
                    "people": people,
                    "promo": l.get("promo_code") or "",
                })
            pays = []
            for p in (o.get("payment_history") or []):
                pd, _pt = when(p.get("date_created"))
                pays.append({
                    "method": p.get("payment_method_display") or "",
                    "date": pd, "amount": num(p.get("amount")) or 0,
                    "status": p.get("status") or "",
                })
            bookings.append({
                "srcClient": cid,
                "number": o.get("number") or "",
                "date": date,
                "status": o.get("status") or "",
                "paidStatus": o.get("payment_status") or "",
                "origin": o.get("origin") or "",
                "note": (o.get("note") or "").strip(),
                "total": num(o.get("total_incl_tax")) or 0,
                "paid": num(o.get("amount_paid")) or 0,
                "due": num(o.get("due_balance")) or 0,
                "lines": lines,
                "payments": pays,
            })

    # only the bookings of the clients that made the cut
    keep = {c["srcId"] for c in clients}
    bookings = [b for b in bookings if b["srcClient"] in keep]
    return {"clients": clients, "bookings": bookings}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="clients.json")
    ap.add_argument("--count", type=int, default=100)
    a = ap.parse_args()
    try:
        data = build(a.count)
    except BloowatchError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    with open(a.out, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=1)
    lines = sum(len(b["lines"]) for b in data["bookings"])
    named = sum(1 for c in data["clients"] if c["email"] or c["phone"])
    print(f"wrote {a.out}: {len(data['clients'])} clients "
          f"({named} with a real email or phone), "
          f"{len(data['bookings'])} bookings, {lines} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
